-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 12:19:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optics
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `optics` ;

-- -----------------------------------------------------
-- Schema optics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optics` DEFAULT CHARACTER SET utf8 ;
USE `optics` ;

-- -----------------------------------------------------
-- Table `optics`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optics`.`address` (
  `id_address` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `address_number` INT UNSIGNED NOT NULL,
  `floor` INT UNSIGNED NULL DEFAULT NULL,
  `door` INT UNSIGNED NULL DEFAULT NULL,
  `postal_code` INT UNSIGNED NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optics`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optics`.`provider` (
  `id_provider` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(45) NOT NULL,
  `phone_number` INT UNSIGNED NOT NULL,
  `fax` INT UNSIGNED NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `address_id_address` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_provider`),
  CONSTRAINT `fk_provider_address1`
    FOREIGN KEY (`address_id_address`)
    REFERENCES `optics`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_provider_address1_idx` ON `optics`.`provider` (`address_id_address` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `optics`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optics`.`employee` (
  `id_employee` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optics`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optics`.`customer` (
  `id_customer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NOT NULL,
  `phone_number` INT UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `costumer_recommend` VARCHAR(45) NULL DEFAULT NULL,
  `registration_date` DATE NOT NULL,
  `address_id_address` INT UNSIGNED NOT NULL,
  `employee_id_employee` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_customer`),
  CONSTRAINT `fk_customer_address1`
    FOREIGN KEY (`address_id_address`)
    REFERENCES `optics`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_employee1`
    FOREIGN KEY (`employee_id_employee`)
    REFERENCES `optics`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `optics`.`customer` (`email` ASC) VISIBLE;

CREATE UNIQUE INDEX `phone_number_UNIQUE` ON `optics`.`customer` (`phone_number` ASC) VISIBLE;

CREATE INDEX `fk_customer_address1_idx` ON `optics`.`customer` (`address_id_address` ASC) VISIBLE;

CREATE INDEX `fk_customer_employee1_idx` ON `optics`.`customer` (`employee_id_employee` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `optics`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optics`.`brand` (
  `id_brand` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(45) NOT NULL,
  `provider_id_provider` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_brand`),
  CONSTRAINT `fk_brand_provider1`
    FOREIGN KEY (`provider_id_provider`)
    REFERENCES `optics`.`provider` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_brand_provider1_idx` ON `optics`.`brand` (`provider_id_provider` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `optics`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optics`.`glasses` (
  `id_glasses` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `graduation_R` DOUBLE NOT NULL,
  `graduation_L` DOUBLE NOT NULL,
  `frame` ENUM('flotant', 'pasta', 'metal') NOT NULL,
  `frame_color` VARCHAR(45) NULL DEFAULT NULL,
  `glass_color` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `brand_id_brand` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_glasses`),
  CONSTRAINT `fk_glasses_brand1`
    FOREIGN KEY (`brand_id_brand`)
    REFERENCES `optics`.`brand` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_glasses_brand1_idx` ON `optics`.`glasses` (`brand_id_brand` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `optics`.`optics_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optics`.`optics_order` (
  `id_opticsOrder` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_date` DATE NOT NULL,
  `glasses_id_glasses` INT UNSIGNED NOT NULL,
  `customer_id_customer` INT UNSIGNED NOT NULL,
  `employee_id_employee` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_opticsOrder`),
  CONSTRAINT `fk_optics_order_glasses`
    FOREIGN KEY (`glasses_id_glasses`)
    REFERENCES `optics`.`glasses` (`id_glasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_optics_order_customer1`
    FOREIGN KEY (`customer_id_customer`)
    REFERENCES `optics`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_optics_order_employee1`
    FOREIGN KEY (`employee_id_employee`)
    REFERENCES `optics`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_optics_order_glasses_idx` ON `optics`.`optics_order` (`glasses_id_glasses` ASC) VISIBLE;

CREATE INDEX `fk_optics_order_customer1_idx` ON `optics`.`optics_order` (`customer_id_customer` ASC) VISIBLE;

CREATE INDEX `fk_optics_order_employee1_idx` ON `optics`.`optics_order` (`employee_id_employee` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
