-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 09:59:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzaShop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaShop` DEFAULT CHARACTER SET utf8 ;
USE `pizzaShop` ;

-- -----------------------------------------------------
-- Table `pizzaShop`.`province`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`province` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`province` (
  `id_province` INT NOT NULL AUTO_INCREMENT,
  `province_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_province`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaShop`.`locality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`locality` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`locality` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `locality_name` VARCHAR(45) NOT NULL,
  `province_id_province` INT NOT NULL,
  PRIMARY KEY (`id_location`),
  CONSTRAINT `fk_location_province`
    FOREIGN KEY (`province_id_province`)
    REFERENCES `pizzaShop`.`province` (`id_province`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_location_province_idx` ON `pizzaShop`.`locality` (`province_id_province` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzaShop`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`address` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `address_number` INT NOT NULL,
  `floor` INT NOT NULL,
  `door` INT NOT NULL,
  `postal_code` INT NOT NULL,
  `locality_id_location` INT NOT NULL,
  PRIMARY KEY (`id_address`),
  CONSTRAINT `fk_address_locality1`
    FOREIGN KEY (`locality_id_location`)
    REFERENCES `pizzaShop`.`locality` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_address_locality1_idx` ON `pizzaShop`.`address` (`locality_id_location` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzaShop`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`customer` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`customer` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `address_id_address` INT NOT NULL,
  PRIMARY KEY (`id_customer`),
  CONSTRAINT `fk_customer_address1`
    FOREIGN KEY (`address_id_address`)
    REFERENCES `pizzaShop`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_customer_address1_idx` ON `pizzaShop`.`customer` (`address_id_address` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_customer_UNIQUE` ON `pizzaShop`.`customer` (`id_customer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzaShop`.`pizza_shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`pizza_shop` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`pizza_shop` (
  `id_pizza_shop` INT NOT NULL AUTO_INCREMENT,
  `shop_name` VARCHAR(45) NOT NULL,
  `address_id_address` INT NOT NULL,
  PRIMARY KEY (`id_pizza_shop`),
  CONSTRAINT `fk_pizza_shop_address1`
    FOREIGN KEY (`address_id_address`)
    REFERENCES `pizzaShop`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pizza_shop_address1_idx` ON `pizzaShop`.`pizza_shop` (`address_id_address` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzaShop`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`employee` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`employee` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_surname` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `pizza_shop_id_pizza_shop` INT NOT NULL,
  PRIMARY KEY (`id_employee`),
  CONSTRAINT `fk_employee_pizza_shop1`
    FOREIGN KEY (`pizza_shop_id_pizza_shop`)
    REFERENCES `pizzaShop`.`pizza_shop` (`id_pizza_shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_employee_pizza_shop1_idx` ON `pizzaShop`.`employee` (`pizza_shop_id_pizza_shop` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzaShop`.`pizza_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`pizza_order` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`pizza_order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME NOT NULL,
  `delivery` VARCHAR(45) NULL,
  `pizza_shop_id_pizza_shop` INT NOT NULL,
  `customer_id_customer` INT NOT NULL,
  `employee_id_employee` INT NOT NULL,
  PRIMARY KEY (`id_order`),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id_customer`)
    REFERENCES `pizzaShop`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_pizza_shop1`
    FOREIGN KEY (`pizza_shop_id_pizza_shop`)
    REFERENCES `pizzaShop`.`pizza_shop` (`id_pizza_shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_employee1`
    FOREIGN KEY (`employee_id_employee`)
    REFERENCES `pizzaShop`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_order_customer1_idx` ON `pizzaShop`.`pizza_order` (`customer_id_customer` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_order_UNIQUE` ON `pizzaShop`.`pizza_order` (`id_order` ASC) VISIBLE;

CREATE INDEX `fk_order_pizza_shop1_idx` ON `pizzaShop`.`pizza_order` (`pizza_shop_id_pizza_shop` ASC) VISIBLE;

CREATE INDEX `fk_order_employee1_idx` ON `pizzaShop`.`pizza_order` (`employee_id_employee` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzaShop`.`pizza_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`pizza_category` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`pizza_category` (
  `id_pizza_category` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pizza_category`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_pizza_category_UNIQUE` ON `pizzaShop`.`pizza_category` (`id_pizza_category` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzaShop`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`product` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NOT NULL,
  `image` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `pizza_category_id_pizza_category` INT NULL,
  PRIMARY KEY (`id_product`),
  CONSTRAINT `fk_product_pizza_category1`
    FOREIGN KEY (`pizza_category_id_pizza_category`)
    REFERENCES `pizzaShop`.`pizza_category` (`id_pizza_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_pizza_category1_idx` ON `pizzaShop`.`product` (`pizza_category_id_pizza_category` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pizzaShop`.`order_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzaShop`.`order_has_product` ;

CREATE TABLE IF NOT EXISTS `pizzaShop`.`order_has_product` (
  `order_id_order` INT NOT NULL,
  `product_id_product` INT NOT NULL,
  `quantity_products` INT NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`order_id_order`, `product_id_product`),
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_id_order`)
    REFERENCES `pizzaShop`.`pizza_order` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_id_product`)
    REFERENCES `pizzaShop`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_order_has_product_product1_idx` ON `pizzaShop`.`order_has_product` (`product_id_product` ASC) VISIBLE;

CREATE INDEX `fk_order_has_product_order1_idx` ON `pizzaShop`.`order_has_product` (`order_id_order` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
